#!/bin/bash
set -e

cd /ruby-bench-suite
git pull --rebase origin master
cp -r discourse/benchmarks/patches/* /discourse/config/initializers/

until pg_isready -h postgres; do
   echo "PG not ready. retrying..."
   sleep 1
done

# For faster Bundle install
echo "gem: --no-document" > ~/.gemrc
gem install bundler -v 1.17.3
gem install facter
gem install CFPropertyList

if [[ ! $(psql -h postgres -U postgres -tc \
  "SELECT 1 FROM pg_database WHERE datname = 'discourse_profile'" | xargs) = 1 ]]; then
  cd /
  createdb -T template0 -h postgres -U postgres discourse_profile
  pg_restore --no-owner -h postgres -U postgres -d discourse_profile discourse_profile.dump
fi

cd /discourse
export DISCOURSE_COMMIT_HASH=$(git rev-parse HEAD)

mv /ruby-bench-suite/discourse/benchmarks/bench.rb script/bench.rb

mv /database.yml config/database.yml
mv /discourse.conf config/discourse.conf
mv /profile_db_generator.rb script/profile_db_generator.rb

rbenv rehash
mv /cache /discourse/vendor/cache

cp Gemfile Gemfile.profile
gems=(actionmailer actionpack actionview activemodel activerecord activesupport railties)
for gem in "${gems[@]}" ; do
  sed -i -re "s/(gem '$gem',\s*').+(')/\1$RAILS_VERSION\2/gi"  Gemfile.profile
done

BUNDLE_GEMFILE=Gemfile.profile bundle install  --without development test -j4 --no-cache --no-prune --path vendor/cache
ruby script/bench.rb -n -b 2 -c 3
