#!/bin/bash
set -e

until pg_isready -h postgres; do
  sleep 1
done

dropdb --if-exists -h postgres -U postgres rubybench
createdb -h postgres -U postgres rubybench

cd /ruby-bench-suite/pg

echo "Running benchmarks using latest suite version"
git pull --rebase origin master

echo "Running benchmarks for latest ruby-pg commit"
PG_MASTER=1 bundle install

cd /ruby-bench-suite/support/setup
bundle install --without mysql

if [ "$INCLUDE_PATTERNS" ]; then
  PATTERNS="--pattern $INCLUDE_PATTERNS"
fi

cd /ruby-bench-suite/pg/benchmarks
PG_MASTER=1 ruby driver.rb $PATTERNS
