#!/bin/bash

set -e

gem install benchmark_driver
gem install benchmark_driver-output-rubybench -v 0.3.0

SCRIPT_NAME="$SCRIPT_NAME.rb"

curl --silent $SCRIPT_URL > $SCRIPT_NAME
curl --silent https://gist.githubusercontent.com/OsamaSayegh/cad2f44426fd5b200909dd924f7378a6/raw/c988b564300943aeb2c1c8cb5158eb468a61e5b5/ruby_runner.rb > ruby_runner.rb

if ruby -c $SCRIPT_NAME; then
  ruby ruby_runner.rb $SCRIPT_NAME
else
  echo "Invalid Ruby syntax. Exiting..."
  exit 1
fi
