#!/bin/bash

set -e

gem install benchmark_driver
gem install benchmark_driver-output-rubybench -v 0.3.1

curl --silent $SCRIPT_URL > $SCRIPT_NAME
curl --silent https://raw.githubusercontent.com/ruby-bench/ruby-bench-docker/master/scripts/ruby/user_scripts/ruby_runner.rb > ruby_runner.rb

ruby ruby_runner.rb $SCRIPT_NAME
