#!/bin/bash
set -e

until pg_isready -h postgres; do
   sleep 1
done

while ! mysqladmin ping -h mysql --silent; do
  echo "mysql - no response"
  sleep 1
done

dropdb --if-exists -h postgres -U postgres rubybench
createdb -h postgres -U postgres rubybench
echo "DROP DATABASE IF EXISTS rubybench" | mysql -u root -h mysql
echo "CREATE DATABASE rubybench" | mysql -u root -h mysql

echo "gem: --no-document" > ~/.gemrc
gem update bundler

cd /ruby-bench-suite/rails
git pull --rebase origin master

if [ "$INCLUDE_PATTERNS" ]; then
  PATTERNS="--pattern $INCLUDE_PATTERNS"
fi

cd /rails
git pull --rebase origin master

if [ -z "$RAILS_COMMIT_HASH" ]; then
  echo "Running benchmarks using latest Rails commit"
else
  echo "Running benchmarks using Rails commit $RAILS_COMMIT_HASH"
  git reset --hard $RAILS_COMMIT_HASH
  bundle install -j4 --without test job doc
fi

if [[ $(git rev-list --count $RAILS_COMMIT_HASH..51211a94bd7a34d80f2412a7f94fefe7366647a5) -gt 0 ]]; then
  sed -i "s/gem 'rack', github: 'rack\/rack', branch: 'master'/gem 'rack'/g" /ruby-bench-suite/rails/Gemfile
fi

cd /ruby-bench-suite/rails
sed -i "s/gem 'rails', github: 'rails'/gem 'rails', path: '\/rails'/g" Gemfile
bundle install -j4

cd /ruby-bench-suite/support/setup
bundle install

echo "Running benchmarks with Rails $RAILS_COMMIT_HASH"
cd /ruby-bench-suite/rails/benchmarks
ruby driver.rb $PATTERNS
