#!/bin/bash
set -e

dropdb --if-exists -h postgres -U postgres rubybench
createdb -h postgres -U postgres rubybench
echo "DROP DATABASE IF EXISTS rubybench" | mysql -u root -h mysql
echo "CREATE DATABASE rubybench" | mysql -u root -h mysql

echo "gem: --no-ri --no-rdoc" > ~/.gemrc
gem update bundler

cd /ruby-bench-suite/sequel
git pull --rebase origin master

if [ "$INCLUDE_PATTERNS" ]; then
  PATTERNS="--pattern $INCLUDE_PATTERNS"
fi

cd /sequel
git pull --rebase origin master

if [ -z "$SEQUEL_COMMIT_HASH" ]; then
  echo "Running benchmarks using latest Sequel commit"
else
  echo "Running benchmarks using Sequel commit $SEQUEL_COMMIT_HASH"
  git reset --hard $SEQUEL_COMMIT_HASH
  bundle install -j4 --without test job doc
fi

cd /ruby-bench-suite/sequel
sed -i "s/gem 'sequel', github: 'jeremyevans\/sequel', branch: 'master'/gem 'sequel', path: '\/sequel'/g" Gemfile
bundle install -j4

cd /ruby-bench-suite/support/setup
bundle install

echo "Running benchmarks with Sequel $SEQUEL_COMMIT_HASH"
cd /ruby-bench-suite/sequel/benchmarks
ruby driver.rb $PATTERNS
